In [1]:
import numpy as np

# one d problem 1
 
# Original array
array = np.zeros(5)
array[0] = 1.9992
array[1] = 1.9978
array[2] = 1.9987
array[3] = 1.9995
array[4] = 1.9990
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[1.9992 1.9978 1.9987 1.9995 1.999 ]

Mean:  1.99884

std:  0.0005817215828899855


In [2]:
# two d problem 1 eps1
 
# Original array
array = np.zeros(5)
array[0] = 2.9852
array[1] = 2.9976
array[2] = 3.0103
array[3] = 3.0149
array[4] = 3.0360
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[2.9852 2.9976 3.0103 3.0149 3.036 ]

Mean:  3.0088

std:  0.017097953093864842


In [3]:
# two d problem 1 eps2
 
# Original array
array = np.zeros(5)
array[0] = 2.0096
array[1] = 1.9974
array[2] = 1.9845
array[3] = 2.0078
array[4] = 2.0054
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[2.0096 1.9974 1.9845 2.0078 2.0054]

Mean:  2.00094

std:  0.009216854127086942


In [4]:
# two d problem 3 eps1
 
# Original array
array = np.zeros(5)
array[0] = 3.9984
array[1] = 3.9846
array[2] = 3.9913
array[3] = 4.0209
array[4] = 4.0116
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[3.9984 3.9846 3.9913 4.0209 4.0116]

Mean:  4.00136

std:  0.01324788284972359


In [5]:
# two d problem 3 eps2
 
# Original array
array = np.zeros(5)
array[0] = 1.9843
array[1] = 2.0067
array[2] = 1.9758
array[3] = 1.9819
array[4] = 1.9841
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[1.9843 2.0067 1.9758 1.9819 1.9841]

Mean:  1.9865599999999997

std:  0.010528741615216868


In [6]:
# two d problem 3 eps3
 
# Original array
array = np.zeros(5)
array[0] = 2.0055
array[1] = 1.9652
array[2] = 1.9949
array[3] = 2.0198
array[4] = 2.0116
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[2.0055 1.9652 1.9949 2.0198 2.0116]

Mean:  1.9994

std:  0.018931983519959027


In [7]:
# two d problem 3 eps4
 
# Original array
array = np.zeros(5)
array[0] = 0.9759
array[1] = 1.0141
array[2] = 0.9887
array[3] = 0.9984
array[4] = 0.9933
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[0.9759 1.0141 0.9887 0.9984 0.9933]

Mean:  0.99408

std:  0.012486216400495386


In [8]:
# two d problem 3 mu1
 
# Original array
array = np.zeros(5)
array[0] = 1.9478
array[1] = 1.9838
array[2] = 1.9731
array[3] = 1.9875
array[4] = 1.9868
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[1.9478 1.9838 1.9731 1.9875 1.9868]

Mean:  1.9758

std:  0.014920991924131587


In [9]:
# three d problem 1 eta1
 
# Original array
array = np.zeros(5)
array[0] = 3.1027
array[1] = 3.0759
array[2] = 3.1422
array[3] = 2.9468
array[4] = 3.0089
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[3.1027 3.0759 3.1422 2.9468 3.0089]

Mean:  3.0553

std:  0.06949523724687892


In [10]:
# three d problem 1 eta2
 
# Original array
array = np.zeros(5)
array[0] = 2.0426
array[1] = 1.9726
array[2] = 2.0226
array[3] = 2.0019
array[4] = 2.0341
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[2.0426 1.9726 2.0226 2.0019 2.0341]

Mean:  2.01476

std:  0.025113390850301443


In [11]:
# three d problem 1 eta3
 
# Original array
array = np.zeros(5)
array[0] = 1.0291
array[1] = 1.1488
array[2] = 1.0564
array[3] = 1.0413
array[4] = 1.0357
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[1.0291 1.1488 1.0564 1.0413 1.0357]

Mean:  1.06226

std:  0.04419921266267084


In [12]:
# three d problem 1 eps1
 
# Original array
array = np.zeros(5)
array[0] = 9.3496
array[1] = 9.2584
array[2] = 9.4896
array[3] = 8.8156
array[4] = 9.0144
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[9.3496 9.2584 9.4896 8.8156 9.0144]

Mean:  9.18552

std:  0.2411726551663765


In [13]:
# three d problem 1 eps2
 
# Original array
array = np.zeros(5)
array[0] = 4.1135
array[1] = 4.0283
array[2] = 4.0408
array[3] = 4.0367
array[4] = 4.1058
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[4.1135 4.0283 4.0408 4.0367 4.1058]

Mean:  4.06502

std:  0.0367431844020087


In [14]:
# three d problem 1 eps3
 
# Original array
array = np.zeros(5)
array[0] = 1.0965
array[1] = 1.1750
array[2] = 1.0571
array[3] = 1.0931
array[4] = 1.0458
print(array)
  
r1 = np.mean(array)
print("\nMean: ", r1)
  
r2 = np.std(array)
print("\nstd: ", r2)

[1.0965 1.175  1.0571 1.0931 1.0458]

Mean:  1.0935

std:  0.04528059186892328
